# index:
#    path: /
#    controller: App\Controller\DefaultController::index
app_lucky_number:
  path: /lucky/number
  controller: App\Controller\LuckyController::number
form_render:
  path: /form
  controller: App\Controller\FormController::render
pokemon_list:
  path: /pokemon
  controller: App\Controller\PokemonController::Index
